#!/bin/sh
# File generated by ocamlbuild

cd /Users/lindseyweiskopf/Documents/reptile

rm -f miniReptile/rgb.o
# Also clean the script itself
rm -f /Users/lindseyweiskopf/Documents/reptile/_build/sanitize.sh
