#!/bin/sh
# File generated by ocamlbuild

cd /home/microc

rm -f miniReptile/canvas.o
rm -f miniReptile/file.o
rm -f miniReptile/pointer.o
rm -f miniReptile/rgb.o
# Also clean the script itself
rm -f /home/microc/_build/sanitize.sh
